# Logistic Regression

# Importing Lib

In [51]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [52]:
data=pd.read_csv("Social_Network_Ads.csv")

In [53]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

# Splitting  the dataset

In [54]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)



In [55]:
print(y_test)

[0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 1 1]


# feature Scalling

In [56]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [57]:
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


# Tranning the KNN  model with tranning data


In [64]:
from sklearn.neighbors import KNeighborsClassifier
clasifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
clasifier.fit(X_train, y_train)

KNeighborsClassifier()

In [65]:
print(clasifier.predict(sc.transform([[30,87000]])))

[0]


# predicting the test set result

In [66]:
print(X_test)
y_pred=clasifier.predict(X_test)


[[ 0.812419   -1.39920777]
 [ 2.0889839   0.52871943]
 [-0.95513241 -0.75656537]
 [ 1.0088136   0.76240757]
 [-0.85693511 -1.22394166]
 [-0.75873781 -0.23076704]
 [ 0.9106163   1.08372877]
 [-0.85693511  0.38266434]
 [ 0.2232352   0.14897619]
 [ 0.4196298  -0.14313399]
 [-0.2677513  -0.14313399]
 [ 1.4998001  -1.04867555]
 [-1.44611891 -0.6397213 ]
 [-1.74071081 -1.36999675]
 [-0.75873781  0.49950841]
 [-0.2677513   1.11293979]
 [ 1.4016028  -0.93183148]
 [ 0.812419    0.11976517]
 [ 0.1250379  -0.8149874 ]
 [ 1.794392   -0.28918908]
 [-1.54431621 -1.25315268]
 [-0.85693511  0.29503128]
 [ 0.9106163  -1.36999675]
 [ 2.0889839   0.17818721]
 [-1.83890811 -1.48684082]
 [ 1.3034055  -1.36999675]
 [ 0.4196298   0.29503128]
 [-0.0713567  -0.49366621]
 [ 1.6961947   1.6095271 ]
 [-1.83890811 -1.42841878]
 [ 0.812419   -0.84419842]
 [-1.83890811  0.0029211 ]
 [-0.169554    2.16453644]
 [-0.95513241  0.26582026]
 [ 0.2232352   1.08372877]
 [-0.2677513   0.14897619]
 [-0.0713567  -0.43524417]
 

In [67]:
print(y_test)

[0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 0 1 0 0
 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 0
 1 0 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 1 1]


In [68]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), axis=1))


[[1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]]


# Making the Confusion matric


In [69]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[59  4]
 [ 3 34]]


0.93