# Ramdom forest



# Importing Lib

In [13]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [14]:
data=pd.read_csv("Social_Network_Ads.csv")

In [15]:
X=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

# Splitting  the dataset

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)



In [17]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


# feature Scalling

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [19]:
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


# Tranning the Random_forest model with tranning data


In [26]:
from sklearn.ensemble import RandomForestClassifier
clasifier = RandomForestClassifier(n_estimators=10,criterion="entropy",random_state=42)
clasifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [27]:
print(clasifier.predict(sc.transform([[30,87000]])))

[0]


# predicting the test set result

In [28]:
print(X_test)
y_pred=clasifier.predict(X_test)
print(y_pred)

[[-0.80480212  0.50496393]
 [-0.01254409 -0.5677824 ]
 [-0.30964085  0.1570462 ]
 [-0.80480212  0.27301877]
 [-0.30964085 -0.5677824 ]
 [-1.10189888 -1.43757673]
 [-0.70576986 -1.58254245]
 [-0.21060859  2.15757314]
 [-1.99318916 -0.04590581]
 [ 0.8787462  -0.77073441]
 [-0.80480212 -0.59677555]
 [-1.00286662 -0.42281668]
 [-0.11157634 -0.42281668]
 [ 0.08648817  0.21503249]
 [-1.79512465  0.47597078]
 [-0.60673761  1.37475825]
 [-0.11157634  0.21503249]
 [-1.89415691  0.44697764]
 [ 1.67100423  1.75166912]
 [-0.30964085 -1.37959044]
 [-0.30964085 -0.65476184]
 [ 0.8787462   2.15757314]
 [ 0.28455268 -0.53878926]
 [ 0.8787462   1.02684052]
 [-1.49802789 -1.20563157]
 [ 1.07681071  2.07059371]
 [-1.00286662  0.50496393]
 [-0.90383437  0.30201192]
 [-0.11157634 -0.21986468]
 [-0.60673761  0.47597078]
 [-1.6960924   0.53395707]
 [-0.11157634  0.27301877]
 [ 1.86906873 -0.27785096]
 [-0.11157634 -0.48080297]
 [-1.39899564 -0.33583725]
 [-1.99318916 -0.50979612]
 [-1.59706014  0.33100506]
 

In [29]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


In [30]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), axis=1))


[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


# Making the Confusion matric


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[65  3]
 [ 3 29]]


0.94

# Visualising traning result

In [35]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

for i in range(1, 42):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=i)
    model = DecisionTreeClassifier(random_state=0)
    model.fit(X_train, y_train)
    print("Random state:", i, "Accuracy:", model.score(X_test, y_test))


Random state: 1 Accuracy: 0.8125
Random state: 2 Accuracy: 0.85
Random state: 3 Accuracy: 0.8375
Random state: 4 Accuracy: 0.85
Random state: 5 Accuracy: 0.875
Random state: 6 Accuracy: 0.85
Random state: 7 Accuracy: 0.8125
Random state: 8 Accuracy: 0.875
Random state: 9 Accuracy: 0.8875
Random state: 10 Accuracy: 0.85
Random state: 11 Accuracy: 0.875
Random state: 12 Accuracy: 0.7875
Random state: 13 Accuracy: 0.8625
Random state: 14 Accuracy: 0.8375
Random state: 15 Accuracy: 0.8625
Random state: 16 Accuracy: 0.875
Random state: 17 Accuracy: 0.8625
Random state: 18 Accuracy: 0.9125
Random state: 19 Accuracy: 0.85
Random state: 20 Accuracy: 0.8375
Random state: 21 Accuracy: 0.9125
Random state: 22 Accuracy: 0.8875
Random state: 23 Accuracy: 0.8625
Random state: 24 Accuracy: 0.85
Random state: 25 Accuracy: 0.8375
Random state: 26 Accuracy: 0.8625
Random state: 27 Accuracy: 0.9
Random state: 28 Accuracy: 0.8
Random state: 29 Accuracy: 0.9
Random state: 30 Accuracy: 0.9125
Random state: 